### ISSUE TITLE
Support guidance and short label

### ISSUE THREAD

**Issue by florianm** [opendatakit/build2xlsform#15]
This issue complements https://github.com/getodk/build/pull/244
Merging #12 and #14 first would provide a clean starting point.

## Guidance
XLSForm supports guidance as `guidance_hint` as per [docs](https://xlsform.org/en/#guidance-hints).

The following steps work and produce the attached file [Short-guidance-export.xlsx](https://github.com/getodk/build2xlsform/files/5678154/Short-guidance-export.xlsx)

* Add `guidance_hint` to `survey-fields` https://github.com/getodk/build2xlsform/blob/master/src/convert.ls#L15
* Add `guidance_hint` to `multilingual-fields` https://github.com/getodk/build2xlsform/blob/master/src/convert.ls#L18
* Add `guidance: \guidance_hint` to https://github.com/getodk/build2xlsform/blob/master/src/convert.ls#L21

## Short label
The XLSForm [spec](https://xlsform.org/) does not mention a short label anywhere. 
Is a short label supported at all?
If it's not supported, then maybe issue a warning about information loss like at https://github.com/getodk/build2xlsform/blob/master/src/convert.ls#L238 ?

**Comment by lognaturel** [comment]
> Is a short label supported at all? 

It's not. Tracked at https://github.com/XLSForm/pyxform/issues/34.

**Comment by florianm** [comment]
Closing this, as guidance hint is now supported.
